.TH musicpager 1 "11 February 2025" "version 0.1"
.SH NAME
music pager \- Is a chord chart display tool
.SH SYNOPSIS
musicpager
.SH DESCRIPTION
Music Pager displays chordpro (www.chordpro.org) formatted chord
charts in a pleasing way for easy reading while playing. It includes
an editing screen to edit charts or create new ones. Music Pager can
create and use set lists. While displaying charts there are hot keys
that allow switching song pages or songs. Changing the song key can
be done on the fly and will be remembered with the set or can be
saved to the song file.
.LP
Music Pager has it's own manual that can be displayed from the main
screen which is more detailed and complete.
.LP
Music pager knows enough chordpro directives to display any of the
downloadable charts tested.
.SH OPTIONS
musicpager does not take any options.
.SH BUGS
Does not know all chordpro directives
.SH AUTHOR
Len Ovens (len@ovenwerks.net)
